version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    command:
      - --auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: domainresolver
    volumes:
      - ./mongodb:/data/db

  domain-resolver:
    build: .
    container_name: domain-resolver
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_URL: mongodb://mongo:27017/nest-domain-resolver
      MONGO_DB: nest-domain-resolver
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo