version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  domain-resolver:
    build: .
    container_name: domain-resolver
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_URL: 'mongodb://mongo:27017/${MONGO_DB}'
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo